[project]
name = "lbm-fno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Liuzihan" }
]
requires-python = ">=3.11"
dependencies = [
    "jax[cuda12]>=0.8.0",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
    "scipy>=1.17.1",
    "tqdm>=4.70.1",
    "warp-lang==1.12.1",
    "xlb>=0.3.1",
]

[project.scripts]
lbm-fno = "lbm_fno:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
