[project]
name = "lbm-fno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Liuzihan" }
]
requires-python = ">=3.11"
dependencies = [
    "ezdxf>=1.4.4",
    "jax[cuda12]>=0.8.0",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "plotly>=7.1.0",
    "pydantic>=2.13.5",
    "pyvista>=0.49.0",
    "pyyaml>=6.0.3",
    "rcpgenerator",
    "scipy>=1.17.1",
    "tqdm>=4.70.1",
    "vtk>=9.7.0",
    "warp-lang==1.12.1",
    "xlb>=0.3.1",
]

[project.scripts]
lbm-fno = "lbm_fno:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
rcpgenerator = { git = "https://github.com/KD-physics/RCPGenerator.git", subdirectory = "python_code/python", rev = "974d703a655b337b93379dbcd1a6eef47386d674" }
